#!/usr/bin/env python3
"""
build_standalone.py – generate standalone.html from index.html
==============================================================

Transforms src/web/static/index.html into src/web/static/standalone.html by:

  1. Injecting sql.js + SheetJS CDN <script> tags into <head>
     (replacing the build marker comment).
  2. Swapping  <script src="app.js">  →  <script src="app-standalone.js">
  3. Prepending an AUTO-GENERATED warning comment.

Run this whenever index.html changes:
    python build_standalone.py

The output (standalone.html) is committed to git so that deploy_static.sh
and the GitHub Actions workflow can consume it directly.
"""

import pathlib
import sys

STATIC = pathlib.Path(__file__).resolve().parent / "src" / "web" / "static"
SRC    = STATIC / "index.html"
DEST   = STATIC / "standalone.html"

# CDN scripts injected into <head> for the static / offline-capable build.
CDN_SCRIPTS = """\
  <!-- sql.js – SQLite compiled to WebAssembly (runs entirely in the browser) -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js"></script>
  <!-- SheetJS – in-browser xlsx export -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>
"""

MARKER_COMMENT = (
    "  <!-- build_standalone.py injects sql.js + SheetJS CDN scripts here"
    " for the static build -->"
)

AUTO_GENERATED_NOTICE = """\
<!-- ═══════════════════════════════════════════════════════════════════════════
     AUTO-GENERATED – do not edit this file directly.
     Edit  src/web/static/index.html  then run:  python build_standalone.py
     ═══════════════════════════════════════════════════════════════════════════ -->
"""


def main() -> None:
    if not SRC.exists():
        sys.exit(f"Source not found: {SRC}")

    html = SRC.read_text(encoding="utf-8")

    # 1. Inject CDN scripts (replace the marker comment)
    if MARKER_COMMENT in html:
        html = html.replace(MARKER_COMMENT, CDN_SCRIPTS.rstrip(), 1)
    else:
        # Fallback: inject just before </head>
        html = html.replace("</head>", CDN_SCRIPTS + "</head>", 1)

    # 2. Swap the app script tag
    html = html.replace(
        '<script src="app.js"></script>',
        '<script src="app-standalone.js"></script>',
        1,
    )

    # 3. Prepend auto-generated notice
    html = AUTO_GENERATED_NOTICE + html

    DEST.write_text(html, encoding="utf-8")
    print(f"✅  Generated {DEST.relative_to(pathlib.Path.cwd())}")


if __name__ == "__main__":
    main()
